services:
  frontend:
    container_name: frontend-app
    build: ./frontend
    restart: unless-stopped
    # environment:
    #   VITE_BASE_URL: "http://localhost:8080"
    ports:
      - 3000:3000
    depends_on:
      - api
    # env_file:
    #   - ./frontend/.env
    volumes:
      - frontend:/var/www/html

  nginx:
    container_name: nginx-server
    build: ./nginx
    ports:
      - 80:80
      # - 443:443
    volumes:
      - frontend:/var/www/html
    depends_on:
      - postgres
      - api
      - frontend

volumes:
  frontend:
